version: '3'
services:
    app:
        build: .
        ports: 
            - 8080:8080 
        depends_on:
            - postgres
        volumes:
            - .:/app
        links:
            - postgres
        command: ./main
    postgres:
        image: postgres:latest
        volumes:
            - "./data/postgres:/var/lib/postgresql/data"
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=test_db
        ports:
          - '5432:5432'

