version: '3'
services:
    app:
        build: .
        ports: 
            - 8080:8080 
        networks:
            - fullstack
        depends_on:
            - postgres
    postgres:
        image: postgres:latest
         
        environment:
          - POSTGRES_USER=${DB_USER}  
          - POSTGRES_PASSWORD=${DB_PASSWORD}
          - POSTGRES_DB=${DB_NAME}
          - DATABASE_HOST=${DB_HOST} 
        ports:
          - '5432:5432'
        networks:
          - fullstack
networks:
  fullstack:
    driver: bridge

